FinalProject/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using FinalProject.Models;

namespace FinalProject.Controllers
{
    public class FileController : Controller
    {
        // GET: File
        [CustomAuthorize(Roles = "Admin,User")]
        public ActionResult Index()
        {
            List<ObjFile> ObjFiles = new List<ObjFile>();
            foreach (string strfile in Directory.GetFiles(Server.MapPath("~/Files")))
            {
                FileInfo fi = new FileInfo(strfile);
                ObjFile obj = new ObjFile();
                obj.File = fi.Name;
                obj.Size = fi.Length;
                obj.Type = GetFileTypeByExtension(fi.Extension);
                ObjFiles.Add(obj);
            }

            return View(ObjFiles);
        }

        public FileResult Download(string fileName)
        {
            string fullPath = Path.Combine(Server.MapPath("~/Files"), fileName);
            byte[] fileBytes = System.IO.File.ReadAllBytes(fullPath);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
        

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Delete(string fileName)
        {
            string fullPath = Path.Combine(Server.MapPath("~/Files"), fileName);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
            return RedirectToAction("Index");
        }
        
        public ActionResult Search(string search)
        {
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/Files"));
            List<ObjFile> files = new List<ObjFile>();
            foreach (string filePath in filePaths)
            {
                files.Add(new ObjFile { File = Path.GetFileName(filePath) });
            }

            return View(files.Where(x=>x.File.Contains(search)));
        }

        public ActionResult ShowPdfInBrowser(string fileName)
        {
            string fullPath = Path.Combine(Server.MapPath("~/Files"), fileName);
            byte[] pdfContent = System.IO.File.ReadAllBytes(fullPath);
            if (pdfContent == null)
            {
                return null;
            }
            var contentDispositionHeader = new System.Net.Mime.ContentDisposition
            {
                Inline = true,
                FileName = "someFilename.pdf"
            };
            Response.Headers.Add("Content-Disposition", contentDispositionHeader.ToString());
            return File(pdfContent, System.Net.Mime.MediaTypeNames.Application.Pdf);
        }

        private string GetFileTypeByExtension(string fileExtension)
        {
            switch (fileExtension.ToLower())
            {
                case ".docx":
                case ".doc":
                    return "Microsoft Word Document";
                case ".xlsx":
                case ".xls":
                    return "Microsoft Excel Document";
                case ".txt":
                    return "Text Document";
                case ".pdf":
                    return "PDF File";
                case ".mp4":
                    return "Video";
                case ".jpg":
                case ".png":
                    return "Image";
                default:
                    return "Unknown";
            }
        }
        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Index(ObjFile doc)
        {
            foreach (var file in doc.files)
            {

                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var filePath = Path.Combine(Server.MapPath("~/Files"), fileName);
                    file.SaveAs(filePath);
                }
            }
            TempData["Message"] = "Files uploaded successfully";
            return RedirectToAction("Index");
        }

    }
}

FinalProject/Views/File/Index.cshtml
@using FinalProject.Models;
@model IEnumerable<ObjFile>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="box-title">
            <b>Files upload and download</b>
        </h3>
    </div>
    <div class="panel-footer">
        <p class="box-title"><b>Total Files till @String.Format("{0 : dddd, MMMM d, yyyy}", DateTime.Now)  : </b><span class="label label-primary">@Model.Count()</span></p>
    </div>
    <div class="panel-footer">
        <p class="box-title"><b>Microsoft Word Document: </b><span class="label label-primary">@Model.Where(x => x.Type.Contains("Microsoft Word Document")).Count()</span></p>


        <p class="box-title"><b>Microsoft Excel Document: </b><span class="label label-primary">@Model.Where(x => x.Type.Contains("Microsoft Excel Document")).Count()</span></p>


        <p class="box-title"><b>Text Document: </b><span class="label label-primary">@Model.Where(x => x.Type.Contains("Text Document")).Count()</span></p>


        <p class="box-title"><b>PDF File: </b><span class="label label-primary">@Model.Where(x => x.Type.Contains("PDF File")).Count()</span></p>


        <p class="box-title"><b>Video: </b><span class="label label-primary">@Model.Where(x => x.Type.Contains("Video")).Count()</span></p>


        <p class="box-title"><b>Image: </b><span class="label label-primary">@Model.Where(x => x.Type.Contains("Image")).Count()</span></p>
    </div>
    <br />
    @using (@Html.BeginForm(null, null, FormMethod.Post,
     new { enctype = "multipart/form-data" }))
    {
        if (TempData["Message"] != null)
        {

            <p style="font-family: Arial; font-size: 16px; font-weight: 200; color: green">@TempData["Message"]</p>
        }
        <table>
            <tr>
                <td>
                    <input type="file" name="files" id="files" multiple="multiple" />
                </td>
                <td>
                    <input type="submit" class="btn" name="submit" />
                </td>
            </tr>

        </table>

    }
    <br />
    @using (Html.BeginForm("Search", "File", FormMethod.Get))
    {
        <input type="text" name="search" placeholder="Enter file name..." />
        <input type="submit" name="submit" value="Search" />
    }

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.File)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Size) (bytes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                Action
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.File)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Size)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <th>
                    @Html.ActionLink("Download", "Download", new { fileName = item.File }) |
                    @Html.ActionLink("Delete", "Delete", new { fileName = item.File }) |
                    @Html.ActionLink("View", "ShowPdfInBrowser", new { fileName = item.File }) (only view PDF File)
                </th>

            </tr>

        }
    </table>
</div>

FinalProject/Views/File/Search.cshtml
@using FinalProject.Models;
@model IEnumerable<ObjFile>



@using (@Html.BeginForm(null, null, FormMethod.Post,
 new { enctype = "multipart/form-data" }))
{
    if (TempData["Message"] != null)
    {

        <p>@TempData["Message"]</p>
    }
    <table>
        <tr>
            <td>
                <h2 style="color: #47bfed">SEARCHING FILES...</h2>
            </td>
        </tr>
    </table>

}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.File)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.File)
            </td>
            <th>
                @Html.ActionLink("Download", "Download", new { fileName = item.File })
            </th>
        </tr>

    }
</table>
<p>
    @Html.ActionLink("Back to list","Index")
</p>